#!/bin/sh
set -eu

lb config noauto \
  --mode debian \
  --distribution trixie \
  --architecture amd64 \
  --archive-areas "main non-free-firmware" \
  --binary-image hdd \
  --bootloaders "grub-pc grub-efi" \
  --debian-installer none \
  --initramfs live-boot \
  --memtest none \
  --apt-recommends false \
  --bootappend-live "boot=live components quiet locales=en_US.UTF-8 keyboard-layouts=us"

